export const form = [
  {
    itForm: {
      grossSalaryIncome: 801276,
      less: {
        rentPaid: 9100,
        actualRentPaid: 109200,
        actualAmount: 31800,
        expenditure: 32612,
        fortyPercent: 306352,
        hra: 31800,
      },
      gspOne: 769476,
      lessTwo: {
        standardDeduction: 50000,
        tax: 2500,
        interest: 0,
        conveyance: 0,
        hill: 0,
        others: 0,
        total: 52500,
      },
      taxableSalaryIncome: 716976,
      add: {
        houseProperty: 0,
        savingBank: 0,
        other: 0,
      },
      grossTotalIncome: 716976,
      lessThree: {
        gpf: 0,
        spf: 2160,
        pli: 15636,
        repayment: 0,
        lic: 65321,
        uti: 0,
        nsc: 0,
        nscInterest: 0,
        equity: 20999,
        tuition: 36000,
        ppf: 0,
        sub: 0,
        invest: 0,
        investInScheme: 24000,
        others: 0,
        total: 164116,
        annualPe: 0,
        annualPension: 0,
        cps: 76588,
        annualCps: 76588,
        totalDeduct: 240704,
        deduction: 150000,
        ded: 0,
        finDed: 0,
        otherSpf: 0,
        otherSpecific: 0,
      },
      grossTaxableIncome: 566976,
      lessFour: {
        one: 3600,
        two: 19364,
        nhis: 22964,
        maintenance: 0,
        medical: 0,
        repay: 0,
        homeLoan: 0,
        cmprf: 0,
        donn: 0,
        donation: 0,
        interest: 0,
        disability: 0,
        others: 0,
        totalDed: 22964,
      },
      netTaxableIncome: 544012,
      roundedNetTaxableIncome: 544010,
      taxOnTotalIncome: {
        tax: 250000,
        nilTaxOn: 250000,
        upto: 0,
        plusOne: 250001,
        value: 500000,
        minValue: 250000,
        fivePer: 12500,
        less: 0,
        twentyPer: 8802,
        thirtyPer: 0,
        surcharge: 0,
        cess: 852,
        totalTaxPayable: 22154,
        lessTaxRelief: 0,
        TaxPayable: 22150,
      },
      taxAlreadyDed: 0,
      netTaxPayable: 22150,
      particularsTutionFee: [
        {
          name: 'DHEERA JEYAHAR',
          class: 'II',
          school: 'ADARSH KENDRYA VIDYALAYA',
          fee: 36000,
        },
        {
          name: '',
          class: '',
          school: '',
          fee: 0,
        },
      ],
      totalTuition: 36000,
      particularsAccured: [
        {
          post: '',
          date: '',
          rate: 0,
          amount: 0,
        },
        {
          post: '',
          date: '',
          rate: 0,
          amount: 0,
        },
      ],
      totalAccured: 0,
      particularsNationalSaving: [
        {
          office: '',
          number: 0,
          date: '',
          amount: 0,
        },
        {
          office: '',
          number: 0,
          date: '',
          amount: 0,
        },
      ],
      totalSavings: 0,
      particularsLic: [
        {
          no: '',
          company: '',
          policy: '',
          amount: 0,
          paid: 0,
        },
        {
          no: '',
          company: '',
          policy: '',
          amount: 0,
          paid: 0,
        },
      ],
      totalLic: 0,
      particularsPremium: [
        {
          no: '308777415',
          company: 'LIC',
          policy: 'JEEVAN LABH(PLAN 836)',
          amount: 1500000,
          paid: 65321,
        },
        {
          no: '',
          company: '',
          policy: ' ',
          amount: 0,
          paid: 0,
        },
        {
          no: '',
          company: '',
          policy: ' ',
          amount: 0,
          paid: 0,
        },
        {
          no: '',
          company: '',
          policy: ' ',
          amount: 0,
          paid: 0,
        },
        {
          no: '',
          company: '',
          policy: ' ',
          amount: 0,
          paid: 0,
        },
        {
          no: '',
          company: '',
          policy: ' ',
          amount: 0,
          paid: 0,
        },
        {
          no: '',
          company: '',
          policy: ' ',
          amount: 0,
          paid: 0,
        },
      ],
      totalPremium: 65321,
      particularsMutualFund: [
        {
          folio: '39588097',
          name: 'QUANT ELSS TAX SAVER',
          date: '',
          lock: '3 YRS',
          other: '',
          amount: 20999,
        },
        {
          folio: '',
          name: '',
          date: '',
          lock: 0,
          other: '',
          amount: 0,
        },
        {
          folio: '',
          name: '',
          date: '',
          lock: 0,
          other: '',
          amount: 0,
        },
      ],
      totalMutualFund: 36000,
    },
    billDrawn: {},
  },
];
