export const form = [
  {
    master: {
      name: 'M P ARUN JEYAHAR',
      designation: 'DEPUTY STATE TAX OFFICER',
      pan: 'BFOPA6244Q',
      schoolOfficeName: 'STATE TAX OFFICE NAGERCOIL 1',
      tan: 'MRIC01323A',
      dob: '1986-07-27',
      age: 37,
      monthlyHouseRentPaid:9100,
      professionalTax:2500,
      interestOnHousingLoan:0,
      repaymentOfHousingLoan:0,
      tuitionFee:0,
      tuition:false
    },
    itForm: {
      grossSalaryIncome: 801276,
      less: {
        rentPaid: 9100,
        actualRentPaid: 109200,
        actualAmount: 31800,
        expenditure: 32612,
        checkSal: false,
        fortyPercent: 306352,
        percentage: 40,
        hra: 31800,
      },
      gspOne: 769476,
      lessTwo: {
        standardDeduction: 50000,
        conveyance: 0,
        hill: 0,
        others: 0,
        total: 52500,
      },
      taxableSalaryIncome: 716976,
      add: {
        houseProperty: 0,
        savingBank: 0,
        other: 0,
      },
      grossTotalIncome: 716976,
      lessThree: {
        gpf: 0,
        spf: 2160,
        pli: 15636,
        repayment: 0,
        lic: 65321,
        uti: 0,
        nsc: 0,
        nscInterest: 0,
        equity: 20999,
        tuition: 36000,
        ppf: 0,
        sub: 0,
        invest: 0,
        investInScheme: 24000,
        others: 0,
        total: 164116,
        annualPe: 0,
        annualPension: 0,
        cps: 76588,
        annualCps: 76588,
        totalDeduct: 240704,
        deduction: 150000,
        ded: 0,
        finDed: 0,
        otherSpf: 0,
        otherSpecific: 0,
      },
      grossTaxableIncome: 566976,
      lessFour: {
        selfSpouseChild: 19364,
        checkAgeSelf: false,
        fatherMother: 0,
        checkAgeFather: false,
        privateHealth: 0,
        one: 3600,
        two: 19364,
        nhis: 22964,
        nhisTwo: 22964,
        maintenance: 0,
        maintenanceTwo: 0,
        medical: 0,
        medicalTwo: 0,
        repay: 0,
        repayTwo: 0,
        homeLoan: 0,
        homeLoanTwo: 0,
        govOne: 0,
        govTwo: 0,
        cmprf: 0,
        donn: 0,
        donation: 0,
        donationTwo: 0,
        interest: 0,
        interestTwo: 0,
        disability: 0,
        disabilityTwo: 0,
        others: 0,
        othersTwo: 0,
        totalDed: 22964,
      },
      netTaxableIncome: 544012,
      roundedNetTaxableIncome: 544010,
      taxOnTotalIncome: {
        tax: 250000,
        nilTaxOn: 250000,
        upto: 0,
        plusOne: 250001,
        value: 500000,
        minValue: 250000,
        fivePer: 12500,
        less: 0,
        valueOne: 500001,
        valueTwo: 1000000,
        valueThree: 44010,
        twentyPer: 8802,
        rOne: 1000000,
        rTwo: 0,
        taxPayable: 0,
        thirtyPer: 0,
        surPer: 0,
        surTax: 0,
        surcharge: 0,
        cess: 21302,
        cessTotal: 852,
        totalTaxPayable: 22154,
        lessTaxRelief: 0,
        checkBox: true,
        lastTaxPayable: 22150,
      },
      taxAlreadyDed: 0,
      netTaxPayable: 22150,
      particularsTutionFee: [
        {
          name: 'DHEERA JEYAHAR',
          class: 'II',
          school: 'ADARSH KENDRYA VIDYALAYA',
          fee: 36000,
        },
        {
          name: '',
          class: '',
          school: '',
          fee: 0,
        },
      ],
      totalTuition: 36000,
      particularsAccured: [
        {
          post: '',
          date: '',
          rate: 0,
          amount: 0,
        },
        {
          post: '',
          date: '',
          rate: 0,
          amount: 0,
        },
      ],
      totalAccured: 0,
      particularsNationalSaving: [
        {
          office: '',
          number: 0,
          date: '',
          amount: 0,
        },
        {
          office: '',
          number: 0,
          date: '',
          amount: 0,
        },
      ],
      totalSavings: 0,
      particularsLic: [
        {
          no: '',
          company: '',
          policy: '',
          amount: 0,
          paid: 0,
        },
        {
          no: '',
          company: '',
          policy: '',
          amount: 0,
          paid: 0,
        },
      ],
      totalLic: 0,
      particularsPremium: [
        {
          no: '308777415',
          company: 'LIC',
          policy: 'JEEVAN LABH(PLAN 836)',
          amount: 1500000,
          paid: 65321,
        },
        {
          no: '',
          company: '',
          policy: ' ',
          amount: 0,
          paid: 0,
        },
        {
          no: '',
          company: '',
          policy: ' ',
          amount: 0,
          paid: 0,
        },
        {
          no: '',
          company: '',
          policy: ' ',
          amount: 0,
          paid: 0,
        },
        {
          no: '',
          company: '',
          policy: ' ',
          amount: 0,
          paid: 0,
        },
        {
          no: '',
          company: '',
          policy: ' ',
          amount: 0,
          paid: 0,
        },
        {
          no: '',
          company: '',
          policy: ' ',
          amount: 0,
          paid: 0,
        },
      ],
      totalPremium: 65321,
      particularsMutualFund: [
        {
          folio: '39588097',
          name: 'QUANT ELSS TAX SAVER',
          date: '',
          lock: '3 YRS',
          other: '',
          amount: 20999,
        },
        {
          folio: '',
          name: '',
          date: '',
          lock: 0,
          other: '',
          amount: 0,
        },
        {
          folio: '',
          name: '',
          date: '',
          lock: 0,
          other: '',
          amount: 0,
        },
      ],
      totalMutualFund: 36000,
    },
    billData : [
      {
        month: '03/23',
        basicPay: 44000,
        pp: '',
        da: 16720,
        hra: 2600,
        cca: '',
        ma: 300,
        spla: '',
        ha: '',
        wa: '',
        convAllow: '',
        bonus: '',
        others: '',
        gross: 63620,
        cps: 6072,
        spf: 70,
        fbf: 110,
        nhis: 300,
        lic_pli: 1303,
        it_cess: '',
        hba_others: '',
        totalDedn: 7855,
        net: 55765,
      },
      {
          month: '04/23',
          basicPay: 44000,
          pp: '',
          da: 16720,
          hra: 2600,
          cca: '',
          ma: 300,
          spla: '',
          ha: '',
          wa: '',
          convAllow: '',
          bonus: '',
          others: '',
          gross: 63620,
          cps: 6072,
          spf: 70,
          fbf: 110,
          nhis: 300,
          lic_pli: 1303,
          it_cess: '',
          hba_others: '',
          totalDedn: 7855,
          net: 55765,
        },
        {
          month: '05/23',
          basicPay: 44000,
          pp: '',
          da: 18480,
          hra: 2600,
          cca: '',
          ma: 300,
          spla: '',
          ha: '',
          wa: '',
          convAllow: '',
          bonus: '',
          others: '',
          gross: 65380,
          cps: 6248,
          spf: 70,
          fbf: 110,
          nhis: 300,
          lic_pli: 1303,
          it_cess: '',
          hba_others: '',
          totalDedn: 8031,
          net: 57349,
        },
        {
          month: '06/23',
          basicPay: 44000,
          pp: '',
          da: 18480,
          hra: 2600,
          cca: '',
          ma: 300,
          spla: '',
          ha: '',
          wa: '',
          convAllow: '',
          bonus: '',
          others: '',
          gross: 65380,
          cps: 6248,
          spf: 70,
          fbf: 110,
          nhis: 300,
          lic_pli: 1303,
          it_cess: '',
          hba_others: '',
          totalDedn: 8031,
          net: 57349,
        },
        {
          month: '07/23',
          basicPay: 44000,
          pp: '',
          da: 18480,
          hra: 2600,
          cca: '',
          ma: 300,
          spla: '',
          ha: '',
          wa: '',
          convAllow: '',
          bonus: '',
          others: '',
          gross: 65380,
          cps: 6248,
          spf: 70,
          fbf: 110,
          nhis: 300,
          lic_pli: 1303,
          it_cess: '',
          hba_others: '',
          totalDedn: 8031,
          net: 57349,
        },
        {
          month: '08/23',
          basicPay: 44000,
          pp: '',
          da: 18480,
          hra: 2600,
          cca: '',
          ma: 300,
          spla: '',
          ha: '',
          wa: '',
          convAllow: '',
          bonus: '',
          others: '',
          gross: 65380,
          cps: 6248,
          spf: 70,
          fbf: 110,
          nhis: 300,
          lic_pli: 1303,
          it_cess: '',
          hba_others: '',
          totalDedn: 8031,
          net: 57349,
        },
        {
          month: '09/23',
          basicPay: 44000,
          pp: '',
          da: 18480,
          hra: 2600,
          cca: '',
          ma: 300,
          spla: '',
          ha: '',
          wa: '',
          convAllow: '',
          bonus: '',
          others: '',
          gross: 65380,
          cps: 6248,
          spf: 70,
          fbf: 110,
          nhis: 300,
          lic_pli: 1303,
          it_cess: '',
          hba_others: '',
          totalDedn: 8031,
          net: 57349,
        },
        {
          month: '10/23',
          basicPay: 44000,
          pp: '',
          da: 18480,
          hra: 2600,
          cca: '',
          ma: 300,
          spla: '',
          ha: '',
          wa: '',
          convAllow: '',
          bonus: '',
          others: '',
          gross: 65380,
          cps: 6248,
          spf: 70,
          fbf: 110,
          nhis: 300,
          lic_pli: 1303,
          it_cess: '',
          hba_others: '',
          totalDedn: 8031,
          net: 57349,
        },
        {
          month: '11/23',
          basicPay: 44000,
          pp: '',
          da: 20240,
          hra: 2600,
          cca: '',
          ma: 300,
          spla: '',
          ha: '',
          wa: '',
          convAllow: '',
          bonus: '',
          others: '',
          gross: 67140,
          cps: 6424,
          spf: 70,
          fbf: 110,
          nhis: 300,
          lic_pli: 1303,
          it_cess: '',
          hba_others: '',
          totalDedn: 8207,
          net: 58933,
        },
        {
          month: '12/23',
          basicPay: 44000,
          pp: '',
          da: 20240,
          hra: 2600,
          cca: '',
          ma: 300,
          spla: '',
          ha: '',
          wa: '',
          convAllow: '',
          bonus: '',
          others: '',
          gross: 67140,
          cps: 6424,
          spf: 70,
          fbf: 110,
          nhis: 300,
          lic_pli: 1303,
          it_cess: '',
          hba_others: '',
          totalDedn: 8207,
          net: 58933,
        },
        {
          month: '01/23',
          basicPay: 45300,
          pp: '',
          da: 20838,
          hra: 2900,
          cca: '',
          ma: 300,
          spla: '',
          ha: '',
          wa: '',
          convAllow: '',
          bonus: '',
          others: '',
          gross: 69338,
          cps: 6614,
          spf: 70,
          fbf: 110,
          nhis: 300,
          lic_pli: 1303,
          it_cess: '',
          hba_others: '',
          totalDedn: 8397,
          net: 60941,
        },
        {
          month: '02/23',
          basicPay: 45300,
          pp: '',
          da: 20838,
          hra: 2900,
          cca: '',
          ma: 300,
          spla: '',
          ha: '',
          wa: '',
          convAllow: '',
          bonus: '',
          others: '',
          gross: 69338,
          cps: 6614,
          spf: 70,
          fbf: 110,
          nhis: 300,
          lic_pli: 1303,
          it_cess: '',
          hba_others: '',
          totalDedn: 8397,
          net: 60941,
        },
        {
          month: 'DA ARR1',
          basicPay: '',
          pp: '',
          da: 1760,
          hra: '',
          cca: '',
          ma: '',
          spla: '',
          ha: '',
          wa: '',
          convAllow: '',
          bonus: '',
          others: '',
          gross: 1760,
          cps: 176,
          spf: '',
          fbf: '',
          nhis: '',
          lic_pli: '',
          it_cess: '',
          hba_others: '',
          totalDedn: 176,
          net: 1584,
        },
        {
          month: 'DA ARR2',
          basicPay: '',
          pp: '',
          da: 7040,
          hra: '',
          cca: '',
          ma: '',
          spla: '',
          ha: '',
          wa: '',
          convAllow: '',
          bonus: '',
          others: '',
          gross: 7040,
          cps: 704,
          spf: '',
          fbf: '',
          nhis: '',
          lic_pli: '',
          it_cess: '',
          hba_others: '',
          totalDedn: 704,
          net: 6336,
        },
        {
          month: 'BONUS',
          basicPay: '',
          pp: '',
          da: '',
          hra: '',
          cca: '',
          ma: '',
          spla: '',
          ha: '',
          wa: '',
          convAllow: '',
          bonus: '',
          others: '',
          gross: '',
          cps: '',
          spf: '',
          fbf: '',
          nhis: '',
          lic_pli: '',
          it_cess: '',
          hba_others: '',
          totalDedn: '',
          net: '',
        },
        {
          month: '',
          basicPay: '',
          pp: '',
          da: '',
          hra: '',
          cca: '',
          ma: '',
          spla: '',
          ha: '',
          wa: '',
          convAllow: '',
          bonus: '',
          others: '',
          gross: '',
          cps: '',
          spf: '',
          fbf: '',
          nhis: '',
          lic_pli: '',
          it_cess: '',
          hba_others: '',
          totalDedn: '',
          net: '',
        },
        {
          month: '',
          basicPay: '',
          pp: '',
          da: '',
          hra: '',
          cca: '',
          ma: '',
          spla: '',
          ha: '',
          wa: '',
          convAllow: '',
          bonus: '',
          others: '',
          gross: '',
          cps: '',
          spf: '',
          fbf: '',
          nhis: '',
          lic_pli: '',
          it_cess: '',
          hba_others: '',
          totalDedn: '',
          net: '',
        },
        {
          month: '',
          basicPay: '',
          pp: '',
          da: '',
          hra: '',
          cca: '',
          ma: '',
          spla: '',
          ha: '',
          wa: '',
          convAllow: '',
          bonus: '',
          others: '',
          gross: '',
          cps: '',
          spf: '',
          fbf: '',
          nhis: '',
          lic_pli: '',
          it_cess: '',
          hba_others: '',
          totalDedn: '',
          net: '',
        },
        {
          month: 'Grand Total',
          basicPay: 530600,
          pp: '',
          da: 235276,
          hra: 31800,
          cca: '',
          ma: 3600,
          spla: '',
          ha: '',
          wa: '',
          convAllow: '',
          bonus: '',
          others: '',
          gross: 801276,
          cps: 76588,
          spf: 840,
          fbf: 1320,
          nhis: 3600,
          lic_pli: 15636,
          it_cess: '',
          hba_others: '',
          totalDedn: 97984,
          net: 703292,
        },
    ],
    billTotal:{
      ActRentPaid: 109200,
      TenPerPayDa:76588,
      RentPaidOverTenPer:32612,
      hra:31800,
      totalIncome:801276,
      LessHRA:31800,
      NetIncome:769476,
    }
  },
];
